from src.utils import test

try:
    print(test())
except Exception as e:
    print(e)